### ISSUE TITLE
Use RDMs generated and indexed iv column instead of calculating.

### ISSUE THREAD

**Issue by 123FLO321** [whitewillem/PMSF#102]
https://github.com/whitewillem/PMSF/blob/c8adf3e8141cf09a3fe105f37898b3fe7f99eb4c/lib/RDM.php#L61 Use indexed column `iv` instead.

https://github.com/whitewillem/PMSF/blob/c8adf3e8141cf09a3fe105f37898b3fe7f99eb4c/lib/RDM.php#L63 Same

https://github.com/whitewillem/PMSF/blob/c8adf3e8141cf09a3fe105f37898b3fe7f99eb4c/lib/RDM.php#L128 Same

https://github.com/whitewillem/PMSF/blob/c8adf3e8141cf09a3fe105f37898b3fe7f99eb4c/lib/RDM.php#L130 Same

**Comment by whitewillem** [comment]
fixed in pokestop-label branch.
