### ISSUE TITLE
$hideQuestsItem and $hideQuestsPokemon not working properly

### ISSUE THREAD

**Issue by xxleevo** [whitewillem/PMSF#108]
Hey
I just noticed that the $hideQuestsPokemon and $hideQuestsItem isnt working properly.
$excludeQuestsPokemon and $excludeQuestsItem is working.

Reproduce the problem:
Set something to automatically hide for quests (pokemon and item, both won't apply)

PMSF installation on a Linux OS (Debian 8)
config.php and also access-config.php tested, Both won't apply the above variables.

**Comment by whitewillem** [comment]
Clear cache. It works fine

**Comment by xxleevo** [comment]
I already cleared my cache - i will test it tomorrow again.
I noticed some other ppl said they have the same problem. I will test multiple Browsers then.

**Comment by xxleevo** [comment]
I also tried multiple browsers, no browser seems to work.

**Comment by cloud9team** [comment]
I was able to resolve this issue by changing lines 1860 and 1861 in pre-index.php from: 
var hideQuestsPokemon = <?php echo $hideQuestsPokemon ? '[]' : $hideQuestsPokemon ?>;
var hideQuestsItem = <?php echo $hideQuestsItem ? '[]' : $hideQuestsItem ?>;
  
To

var hideQuestsPokemon = <?php echo $noQuestsPokemon ? '[]' : $hideQuestsPokemon ?>;
var hideQuestsItem = <?php echo $noQuestsItem ? '[]' : $hideQuestsItem ?>;

This follows the same format as previous var hidePokemon

**Comment by whitewillem** [comment]
This is fixes in develop branch.
