### ISSUE TITLE
Ex Gym Markers not shown on map

### ISSUE THREAD

**Issue by ColdShadow80** [whitewillem/PMSF#137]
Ex Gym Markers not shown on map in Master branch in MAD database
Error is present both in Rocketmaps and Monocle databases.

field "is_ex_raid_eligible" is present and sset to 1 in gym table, but map does not show it.
Also map does not allow manual tagging of Ex Gym, probably query points to wrong or outdated field in database.

**Comment by TiMXL73** [comment]
just an fyi: Ex Gym Markers issue is already fixed and working properly in develop branch (commit https://github.com/whitewillem/PMSF/commit/272240a93db3cf5ee7af841ff2ace5349e6295e5)

**Comment by ColdShadow80** [comment]
Any ETA for this fix to merged into master?

**Comment by whitewillem** [comment]
Its in develop. Should be merged with master soon
