### ISSUE TITLE
getting error in php log on latest commit

### ISSUE THREAD

**Issue by cloud9team** [whitewillem/PMSF#147]
on develop branch after latest commit error logs read "PHP Warning:  Use of undefined constant quest_pokemon_id - assumed 'quest_pokemon_id' (this will throw an Error in a future version of PHP)" index.php on line 363

Changing `$data[] = $pokestop[quest_pokemon_id];` to `$data[] = $pokestop['quest_pokemon_id'];`
resolved the issue. 
this may be more related to php versions, but the warning is pretty noisy in the error logs.

**Comment by whitewillem** [comment]
fixed in latest develop. thx for pointing it out.
